vim.cmd "let g:tmpl_search_paths = ['~/.config/nvim/templates']"
vim.cmd "let g:tmpl_author_name = 'Justin Kachele'"
vim.cmd "let g:tmpl_author_hostname = 'jkachele@hyperion'"
vim.cmd "let g:tmpl_author_email = 'justin@kachele.com'"
vim.cmd "let g:tmpl_license = 'GNU GPL-3.0'"
