-- vim.cmd([[
--     let overlength#default_overlength = 80
--
--     call overlength#set_overlength('python', 79)
--
--     " To disable highlighting in multiple fts at once
--     call overlength#disable_filetypes(['markdown', 'term', 'lua', 'NvimTree'])
-- ]])
